#%RAML 1.0
title: 2017 HMIS API
version: 1.0.0
mediaType: application/json
protocols:
  - HTTPS
baseUri: 'https://www.hmislynk.com/hmis-clientapi-v2017/rest/v2017'
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
types:
  affiliation_id : !include types/affiliation_id.json
  affiliation_id_only : !include types/affiliation_id_only.json
  affiliations : !include types/affiliations.json
  affiliations_ids : !include types/affiliations_ids.json
  client_id : !include types/client_id.json
  client : !include types/client.json
  clients_id_only : !include types/client_id_only.json
  clients_ids : !include types/clients_ids.json
  contact : !include types/contact.json
  contact_id : !include types/contact_id.json
  contact_id_only : !include types/contact_id_only.json
  contacts_ids : !include types/contacts_ids.json
  date_of_engagement : !include types/date_of_engagement.json
  date_of_engagement_id : !include types/date_of_engagement_id.json
  date_of_engagement_id_only : !include types/date_of_engagement_id_only.json
  date_of_engagements_ids : !include types/date_of_engagements_ids.json
  disability : !include types/disability.json
  disability_id : !include types/disability_id.json
  disability_id_only : !include types/disability_id_only.json
  disabilities_ids : !include types/disabilities_ids.json
  domestic_violence : !include types/domestic_violence.json
  domestic_violence_id : !include types/domestic_violence_id.json
  domestic_violence_id_only : !include types/domestic_violence_id_only.json
  domestic_violences_ids : !include types/domestic_violences_ids.json
  education : !include types/education.json
  education_id : !include types/education_id.json
  education_id_only : !include types/education_id_only.json
  education_ids : !include types/education_ids.json
  educations_ids : !include types/educations_ids.json
  employment : !include types/employment.json
  employment_id : !include types/employment_id.json
  employment_id_only : !include types/employment_id_only.json
  employments_ids : !include types/employments_ids.json
  enrollment : !include types/enrollment.json
  enrollment_coc : !include types/enrollment_coc.json
  enrollment_coc_id : !include types/enrollment_coc_id.json
  enrollment_coc_id_only : !include types/enrollment_coc_id_only.json
  enrollment_cocs_ids : !include types/enrollment_cocs_ids.json
  enrollment_id : !include types/enrollment_id.json
  enrollment_id_only : !include types/enrollment_id_only.json
  enrollments_ids : !include types/enrollments_ids.json
  entry_rhsp : !include types/entry_rhsp.json
  entry_rhsp_id : !include types/entry_rhsp_id.json
  entry_rhsp_id_only : !include types/entry_rhsp_id_only.json
  entry_rhsps_ids : !include types/entry_rhsps_ids.json
  entry_rhy : !include types/entry_rhy.json
  entry_rhy_id : !include types/entry_rhy_id.json
  entry_rhy_id_only : !include types/entry_rhy_id_only.json
  entry_rhys_ids : !include types/entry_rhys_ids.json
  entry_ssvf : !include types/entry_ssvf.json
  entry_ssvf_id : !include types/entry_ssvf_id.json
  entry_ssvf_id_only : !include types/entry_ssvf_id_only.json
  entry_ssvfs_ids : !include types/entry_ssvfs_ids.json
  exit : !include types/exit.json
  exit_housing_assessment : !include types/exit_housing_assessment.json
  exit_housing_assessment_id : !include types/exit_housing_assessment_id.json
  exit_housing_assessments_ids : !include types/exit_housing_assessments_ids.json
  exit_id : !include types/exit_id.json
  exit_id_only : !include types/exit_id_only.json
  exit_path : !include types/exit_path.json
  exit_path_id : !include types/exit_path_id.json
  exit_path_id_only : !include types/exit_path_id_only.json
  exit_paths_ids : !include types/exit_paths_ids.json
  exit_rhy : !include types/exit_rhy.json
  exit_rhy_id : !include types/exit_rhy_id.json
  exit_rhy_id_only : !include types/exit_rhy_id_only.json
  exit_rhys_ids : !include types/exit_rhys_ids.json
  exit_housing_assessment_id_only : !include types/exit_housing_assessment_id_only.json
  exits_ids : !include types/exits_ids.json
  funder_id : !include types/funder_id.json
  funder_id_only : !include types/funder_id_only.json
  funders : !include types/funders.json
  funders_ids : !include types/funders_ids.json
  health_insurance : !include types/health_insurance.json
  health_insurance_id : !include types/health_insurance_id.json
  health_insurances_ids : !include types/health_insurances_ids.json
  health_status : !include types/health_status.json
  health_status_id : !include types/health_status_id.json
  health_statuses_ids : !include types/health_statuses_ids.json
  healthinsurance_id_only : !include types/healthinsurance_id_only.json
  healthstatus_id_only : !include types/healthstatus_id_only.json
  housing_assessment_disposition : !include types/housing_assessment_disposition.json
  housing_assessment_disposition_id : !include types/housing_assessment_disposition_id.json
  housing_assessment_disposition_id_only : !include types/housing_assessment_disposition_id_only.json
  housing_assessment_dispositions_ids : !include types/housing_assessment_dispositions_ids.json
  income_and_source : !include types/income_and_source.json
  income_and_source_id : !include types/income_and_source_id.json
  income_and_source_id_only : !include types/income_and_source_id_only.json
  income_and_sources_ids : !include types/income_and_sources_ids.json
  inventories_ids : !include types/inventories_ids.json
  inventory : !include types/inventory.json
  inventory_id : !include types/inventory_id.json
  inventory_id_only : !include types/inventory_id_only.json
  medical_assistance : !include types/medical_assistance.json
  medical_assistance_id : !include types/medical_assistance_id.json
  medical_assistance_id_only : !include types/medical_assistance_id_only.json
  medical_assistances_ids : !include types/medical_assistances_ids.json
  non_cash_benefits : !include types/non_cash_benefits.json
  non_cash_benefits_id : !include types/non_cash_benefits_id.json
  non_cash_benefits_id_only : !include types/non_cash_benefits_id_only.json
  non_cash_benefitses_ids : !include types/non_cash_benefitses_ids.json
  organization : !include types/organization.json
  organization_id : !include types/organization_id.json
  organization_id_only : !include types/organization_id_only.json
  organizations_ids : !include types/organizations_ids.json
  path_status : !include types/path_status.json
  path_status_id : !include types/path_status_id.json
  path_status_id_only : !include types/path_status_id_only.json
  path_statuses_ids : !include types/path_statuses_ids.json
  project : !include types/project.json
  project_coc : !include types/project_coc.json
  project_coc_id : !include types/project_coc_id.json
  project_coc_id_only : !include types/project_coc_id_only.json
  project_cocs_ids : !include types/project_cocs_ids.json
  project_id : !include types/project_id.json
  projects_id_only : !include types/projects_id_only.json
  projects_ids : !include types/projects_ids.json
  residential_move_in_date : !include types/residential_move_in_date.json
  residential_move_in_date_id : !include types/residential_move_in_date_id.json
  residential_move_in_date_id_only : !include types/residential_move_in_date_id_only.json
  residential_move_in_dates_ids : !include types/residential_move_in_dates_ids.json
  service_fa_referral : !include types/service_fa_referral.json
  service_fa_referral_id : !include types/service_fa_referral_id.json
  service_fa_referral_id_only : !include types/service_fa_referral_id_only.json
  service_fa_referrals_ids : !include types/service_fa_referrals_ids.json
  site : !include types/site.json
  site_id : !include types/site_id.json
  site_id_only : !include types/site_id_only.json
  sites_ids : !include types/sites_ids.json
  veteran_info : !include types/veteran_info.json
  veteran_info_id : !include types/veteran_info_id.json
  veteran_info_id_only : !include types/veteran_info_id_only.json
  veteran_infos_ids : !include types/veteran_infos_ids.json
resourceTypes:
  collection: !include types/collection.raml
  member: !include types/member.raml
/clients:
    type:
      collection:
        schema_ids: clients_ids
        schema_ids_example: !include examples/clients_ids_example.json
        schema: client
        schema_example: !include examples/client_example.json
        schema_id_example: !include examples/client_id_example.json
    /{clientid}:
      type:
         member:
          schema: client
          schema_id: client_id
          schema_id_example: !include examples/client_id_example.json
          schema_example: !include examples/client_example.json
      /enrollments:
        type:
          collection:
            schema: enrollment
            schema_ids: enrollments_ids
            schema_ids_example: !include ./examples/enrollments_ids_example.json
            schema_example: !include ./examples/enrollment_example.json
            schema_id_example: !include ./examples/enrollment_id_example.json
        /{enrollmentid}:
          type:
            member:
              schema: enrollment
              schema_id: enrollment_id
              schema_id_example: !include ./examples/enrollment_id_example.json
              schema_example: !include ./examples/enrollment_example.json
          /enrollment_cocs:
            type:
              collection:
                schema_id: enrollment_coc_id
                schema: enrollment_coc
                schema_ids: enrollment_cocs_ids
                schema_ids_example: !include ./examples/enrollment_cocs_ids_example.json
                schema_example: !include ./examples/enrollment_coc_example.json
                schema_id_example: !include ./examples/enrollment_coc_id_example.json
            /{enrollment_cocid}:
              type:
                member:
                  schema: enrollment_coc
                  schema_id: enrollment_coc_id
                  schema_id_example: !include ./examples/enrollment_coc_id_example.json
                  schema_example: !include ./examples/enrollment_coc_example.json
          /educations:
            type:
              collection:
                schema: education
                schema_ids: educations_ids
                schema_ids_example: !include ./examples/educations_ids_example.json
                schema_example: !include ./examples/education_example.json
                schema_id_example: !include ./examples/education_id_example.json
            /{educationid}:
              type:
                member:
                  schema: education
                  schema_id: education_id
                  schema_id_example: !include ./examples/education_id_example.json
                  schema_example: !include ./examples/education_example.json
          /contacts:
            type:
              collection:
                schema: contact
                schema_ids: contacts_ids
                schema_ids_example: !include ./examples/contacts_ids_example.json
                schema_example: !include ./examples/contact_example.json
                schema_id_example: !include ./examples/contact_id_example.json
            /{contactid}:
              type:
                member:
                  schema: contact
                  schema_id: contact_id
                  schema_id_example: !include ./examples/contact_id_example.json
                  schema_example: !include ./examples/contact_example.json
          /dateofengagements:
            type:
              collection:
                schema: date_of_engagement
                schema_ids: date_of_engagements_ids
                schema_example: !include ./examples/date_of_engagement_example.json
                schema_ids_example: !include ./examples/date_of_engagements_ids_example.json
                schema_id_example: !include ./examples/date_of_engagement_id_example.json
            /{dateofengagementid}:
              type:
                member:
                  schema: date_of_engagement
                  schema_id: date_of_engagement_id
                  schema_id_example: !include ./examples/date_of_engagement_id_example.json
                  schema_example: !include ./examples/date_of_engagement_example.json
          /disabilities:
            type:
              collection:
                schema: disability
                schema_ids: disabilities_ids
                schema_example: !include ./examples/disability_example.json
                schema_ids_example: !include ./examples/disabilities_ids_example.json
                schema_id_example: !include ./examples/disability_id_example.json
            /{disabilityid}:
              type:
                member:
                  schema: disability
                  schema_id: disability_id
                  schema_example: !include ./examples/disability_example.json
                  schema_id_example: !include ./examples/disability_id_example.json
          /domesticviolences:
            type:
              collection:
                schema: domestic_violence
                schema_ids: domestic_violences_ids
                schema_example: !include ./examples/domestic_violence_example.json
                schema_ids_example: !include ./examples/domestic_violences_ids_example.json
                schema_id_example: !include ./examples/domestic_violence_id_example.json
            /{domesticviolenceid}:
              type:
                member:
                  schema: domestic_violence
                  schema_id: domestic_violence_id
                  schema_example: !include ./examples/domestic_violence_example.json
                  schema_id_example: !include ./examples/domestic_violence_id_example.json
          /employments:
            type:
              collection:
                schema: employment
                schema_ids: employments_ids
                schema_example: !include ./examples/employment_example.json
                schema_ids_example: !include ./examples/employments_ids_example.json
                schema_id_example: !include ./examples/employment_id_example.json
            /{employmentid}:
              type:
                member:
                  schema: employment
                  schema_id: employment_id
                  schema_id_example: !include ./examples/employment_id_example.json
                  schema_example: !include ./examples/employment_example.json
          /exits:
            type:
              collection:
                schema: exit
                schema_ids: exits_ids
                schema_example: !include ./examples/exit_example.json
                schema_ids_example: !include ./examples/exits_ids_example.json
                schema_id_example: !include ./examples/exit_id_example.json
            /{exitid}:
              type:
                member:
                  schema: exit
                  schema_id: exit_id
                  schema_id_example: !include ./examples/exit_id_example.json
                  schema_example: !include ./examples/exit_example.json
              /exithousingassessments:
                type:
                  collection:
                    schema: exit_housing_assessment
                    schema_ids: exit_housing_assessments_ids
                    schema_example: !include ./examples/exit_housing_assessment_example.json
                    schema_ids_example: !include ./examples/exit_housing_assessments_ids_example.json
                    schema_id_example: !include ./examples/exit_housing_assessment_id_example.json
                /{exithousingassessmentid}:
                  type:
                    member:
                      schema: exit_housing_assessment
                      schema_id: exit_housing_assessment_id
                      schema_example: !include ./examples/exit_housing_assessment_example.json
                      schema_id_example: !include ./examples/exit_housing_assessment_id_example.json
              /housingassessmentdispositions:
                type:
                  collection:
                    schema: housing_assessment_disposition
                    schema_ids: housing_assessment_dispositions_ids
                    schema_example: !include ./examples/housing_assessment_disposition_example.json
                    schema_ids_example: !include ./examples/housing_assesment_dispositions_ids_example.json
                    schema_id_example: !include ./examples/housing_assessment_disposition_id_example.json
                /{housingassessmentdispositionid}:
                  type:
                    member:
                      schema: housing_assessment_disposition
                      schema_id: housing_assessment_disposition_id
                      schema_example: !include ./examples/housing_assessment_disposition_example.json
                      schema_id_example: !include ./examples/housing_assessment_disposition_id_example.json
              /exitpaths:
                type:
                  collection:
                    schema: exit_path
                    schema_ids: exit_paths_ids
                    schema_example: !include ./examples/exit_path_example.json
                    schema_ids_example: !include ./examples/exit_paths_ids_example.json
                    schema_id_example: !include ./examples/exit_path_id_example.json
                /{exitpathid}:
                  type:
                    member:
                      schema: exit_path
                      schema_id: exit_path_id
                      schema_example: !include ./examples/exit_path_example.json
                      schema_id_example: !include ./examples/exit_path_id_example.json
              /exitrhys:
                type:
                  collection:
                    schema: exit_rhy
                    schema_ids: exit_rhys_ids
                    schema_example: !include ./examples/exit_rhy_example.json
                    schema_ids_example: !include ./examples/exit_rhys_ids_example.json
                    schema_id_example: !include ./examples/exit_rhy_id_example.json
                /{exitrhyid}:
                  type:
                    member:
                      schema: exit_rhy
                      schema_id: exit_rhy_id
                      schema_example: !include ./examples/exit_rhy_example.json
                      schema_id_example: !include ./examples/exit_rhy_id_example.json
          /healthinsurances:
            type:
              collection:
                schema: health_insurance
                schema_ids: health_insurances_ids
                schema_example: !include ./examples/HealthInsurance_example.json
                schema_ids_example: !include ./examples/HealthInsurances_ids_example.json
                schema_id_example: !include ./examples/id_healthinsurance_example.json
            /{healthinsuranceid}:
              type:
                member:
                  schema: healthinsurance
                  schema_id: healthinsurance_id
                  schema_example: !include ./examples/HealthInsurance_example.json
                  schema_id_example: !include ./examples/HealthInsurance_id_example.json
          /healthstatuses:
            type:
              collection:
                schema_id: id_healthstatus
                schema: healthstatus
                schema_ids: healthstatus_ids
                schema_example: !include ./examples/HealthStatus_example.json
                schema_ids_example: !include ./examples/HealthStatus_ids_example.json
                schema_id_example: !include ./examples/id_healthstatus_example.json
            /{healthstatusid}:
              type:
                member:
                  schema: healthstatus
                  schema_id: healthstatus_id
                  schema_example: !include ./examples/HealthStatus_example.json
                  schema_id_example: !include ./examples/HealthStatus_id_example.json
          /incomeandsources:
            type:
              collection:
                schema_id: id_incomeandsources
                schema: incomeandsource
                schema_ids: incomeandsources_ids
                schema_example: !include ./examples/IncomeAndSource_example.json
                schema_ids_example: !include ./examples/IncomeAndSources_ids_example.json
                schema_id_example: !include ./examples/id_incomeandsource_example.json
            /{incomeandsourcesid}:
              type:
                member:
                  schema: incomeandsource
                  schema_id: incomeandsource_id
                  schema_example: !include ./examples/IncomeAndSource_example.json
                  schema_id_example: !include ./examples/IncomeAndSource_id_example.json
          /medicalassistences:
            type:
              collection:
                schema_id: id_medicalassistances
                schema: medicalassistance
                schema_ids: medicalassistances_ids
                schema_example: !include ./examples/MedicalAssistance_example.json
                schema_ids_example: !include ./examples/MedicalAssistances_ids_example.json
                schema_id_example: !include ./examples/id_medicalassistance_example.json
            /{medicalassistancesid}:
              type:
                member:
                  schema: medicalassistance
                  schema_id: medicalassistances_id
                  schema_example: !include ./examples/MedicalAssistance_example.json
                  schema_id_example: !include ./examples/MedicalAssistances_id_example.json
          /noncashbenefits:
            type:
              collection:
                schema_id: id_noncashbenefits
                schema: noncashbenefits
                schema_ids: noncashbenefits_ids
                schema_example: !include ./examples/NonCashBenefits_example.json
                schema_ids_example: !include ./examples/NonCashBenefits_ids_example.json
                schema_id_example: !include ./examples/id_noncashbenefits_example.json
            /{noncashbenefitsid}:
              type:
                member:
                  schema: noncashbenefits
                  schema_id: noncashbenefits_id
                  schema_example: !include ./examples/NonCashBenefits_example.json
                  schema_id_example: !include ./examples/NonCashBenefits_id_example.json
          /residentialmoveindates:
            type:
              collection:
                schema_id: id_residentialmoveindate
                schema: residentialmoveindate
                schema_ids: residentialmoveindate_ids
                schema_example: !include ./examples/ResidentialMoveInDate_example.json
                schema_ids_example: !include ./examples/ResidentialMoveInDate_ids_example.json
                schema_id_example: !include ./examples/id_residentialmoveindate_example.json
            /{residentialmoveindatesid}:
              type:
                member:
                  schema: residentialmoveindate
                  schema_id: residentialmoveindate_id
                  schema_example: !include ./examples/ResidentialMoveInDate_example.json
                  schema_id_example: !include ./examples/ResidentialMoveInDate_id_example.json
          /pathstatuses:
            type:
              collection:
                schema_id: id_pathstatus
                schema: pathstatus
                schema_ids: pathstatus_ids
                schema_example: !include ./examples/PathStatus_example.json
                schema_ids_example: !include ./examples/PathStatus_ids_example.json
                schema_id_example: !include ./examples/id_pathstatus_example.json
            /{pathstatusid}:
              type:
                member:
                  schema: pathstatus
                  schema_id: pathstatus_id
                  schema_example: !include ./examples/PathStatus_example.json
                  schema_id_example: !include ./examples/PathStatus_id_example.json
          /entryrhsps:
            type:
              collection:
                schema_id: id_entryrhsp
                schema: entryrhsp
                schema_ids: entryrhsp_ids
                schema_example: !include ./examples/entryrhsp_example.json
                schema_ids_example: !include ./examples/entryrhsp_ids_example.json
                schema_id_example: !include ./examples/id_entryrhsp_example.json
            /{entryrhspid}:
              type:
                member:
                  schema: entryrhsp
                  schema_id: entryrhsp_id
                  schema_example: !include ./examples/entryrhsp_example.json
                  schema_id_example: !include ./examples/entryrhsp_id_example.json
          /entryrhys:
            type:
              collection:
                schema_id: id_entryrhy
                schema: entryrhy
                schema_ids: entryrhy_ids
                schema_example: !include ./examples/entryrhy_example.json
                schema_ids_example: !include ./examples/entryrhy_ids_example.json
                schema_id_example: !include ./examples/id_entryrhy_example.json
            /{entryrhyid}:
              type:
                member:
                  schema: entryrhy
                  schema_id: entryrhy_id
                  schema_example: !include ./examples/entryrhy_example.json
                  schema_id_example: !include ./examples/entryrhy_id_example.json
          /entryssvfs:
            type:
              collection:
                schema_id: id_entryssvf
                schema: entryssvf
                schema_ids: entryssvf_ids
                schema_example: !include ./examples/entryssvf_example.json
                schema_ids_example: !include ./examples/entryssvf_ids_example.json
                schema_id_example: !include ./examples/id_entryssvf_example.json
            /{entryssvfid}:
              type:
                member:
                  schema: entryssvf
                  schema_id: entryssvf_id
                  schema_example: !include ./examples/entryssvf_example.json
                  schema_id_example: !include ./examples/entryssvf_id_example.json
          /servicefareferrals:
            type:
              collection:
                schema_id: id_servicefareferral
                schema: servicefareferral
                schema_ids: servicefareferrals_ids
                schema_example: !include ./examples/ServiceFaReferral_example.json
                schema_ids_example: !include ./examples/ServiceFaReferrals_ids_example.json
                schema_id_example: !include ./examples/id_servicefareferral_example.json
            /{servicefareferralid}:
              type:
                member:
                  schema: servicefareferral
                  schema_id: servicefareferral_id
                  schema_example: !include ./examples/ServiceFaReferral_example.json
                  schema_id_example: !include ./examples/ServiceFaReferral_id_example.json
      /veteraninfos:
        type:
          collection:
            schema_id: id_veteraninfo
            schema: veteraninfo
            schema_ids: veteraninfo_ids
            schema_example: !include ./examples/VeteranInfo_example.json
            schema_ids_example: !include ./examples/VeteranInfo_ids_example.json
            schema_id_example: !include ./examples/id_veteraninfo_example.json
        /{veteraninfoid}:
          type:
            member:
              schema: veteraninfo
              schema_id: veteraninfo_id
              schema_example: !include ./examples/VeteranInfo_example.json
              schema_id_example: !include ./examples/VeteranInfo_id_example.json
/projects:
  type:
    collection:
      schema_id: id_projects
      schema: project
      schema_ids: projects_ids
      schema_example: !include ./examples/Project_example.json
      schema_ids_example: !include ./examples/Projects_ids_example.json
      schema_id_example: !include ./examples/id_project_example.json
  /{projectsid}:
    type:
      member:
        schema: project
        schema_id: projects_id
        schema_id_example: !include ./examples/Projects_id_example.json
        schema_example: !include ./examples/Project_example.json
    /projectcocs:
      type:
        collection:
          schema_id: id_projectcoc
          schema: projectcoc
          schema_ids: projectcoc_ids
          schema_example: !include ./examples/Projectcoc_example.json
          schema_ids_example: !include ./examples/Projectcoc_ids_example.json
          schema_id_example: !include ./examples/id_Projectcoc_example.json
      /{projectcocid}:
        type:
          member:
            schema: projectcoc
            schema_id: projectcoc_id
            schema_example: !include ./examples/Projectcoc_example.json
            schema_id_example: !include ./examples/Projectcoc_id_example.json
    /inventories:
      type:
        collection:
          schema_id: id_inventories
          schema: inventories
          schema_ids: inventories_ids
          schema_example: !include ./examples/Inventories_example.json
          schema_ids_example: !include ./examples/Inventories_ids_example.json
          schema_id_example: !include ./examples/id_inventories_example.json
      /{inventoriesid}:
        type:
          member:
            schema: inventories
            schema_id: inventories_id
            schema_id_example: !include ./examples/Inventories_id_example.json
            schema_example: !include ./examples/Inventories_example.json
    /sites:
      type:
        collection:
          schema_id: id_sites
          schema: sites
          schema_ids: sites_ids
          schema_example: !include ./examples/Sites_example.json
          schema_ids_example: !include ./examples/Sites_ids_example.json
          schema_id_example: !include ./examples/id_sites_example.json
      /{sitesid}:
        type:
          member:
            schema: sites
            schema_id: sites_id
            schema_example: !include ./examples/Sites_example.json
            schema_id_example: !include ./examples/Sites_id_example.json
    /funders:
      type:
        collection:
          schema_id: id_funders
          schema: funders
          schema_ids: funders_ids
          schema_example: !include ./examples/Funders_example.json
          schema_ids_example: !include ./examples/Funders_ids_example.json
          schema_id_example: !include ./examples/id_funders_example.json
      /{fundersid}:
        type:
          member:
            schema: funders
            schema_id: funder_id
            schema_example: !include ./examples/Funders_example.json
            schema_id_example: !include ./examples/Funder_id_example.json
    /affiliations:
      type:
        collection:
          schema_id: id_affiliation
          schema: affiliations
          schema_ids: affiliations_ids
          schema_example: !include ./examples/Affiliations_example.json
          schema_ids_example: !include ./examples/Affiliation_ids_example.json
          schema_id_example: !include ./examples/id_affiliation_example.json
      /{affiliationid}:
        type:
          member:
            schema: affiliations
            schema_id: affiliation_id
            schema_example: !include ./examples/Affiliations_example.json
            schema_id_example: !include ./examples/Affiliation_id_example.json
/organizations:
  type:
    collection:
      schema_id: id_organization
      schema: organization
      schema_ids: organization_ids
      schema_example: !include ./examples/organization_example.json
      schema_ids_example: !include ./examples/organization_ids_example.json
      schema_id_example: !include ./examples/id_organization_example.json
  /{organizationid}:
    type:
      member:
        schema: organization
        schema_id: organization_id
        schema_id_example: !include ./examples/organization_id_example.json
        schema_example: !include ./examples/organization_example.json
          /search:
            '/{searchentity}':
              get:
                description: |
                  The Search API is optimized to find the specific entity you're looking for (e.g., a client, enrollments, etc.).It's designed to  find the one result you're looking for (or maybe the few results you're looking for). Currently hmislynk supporting search on 'clients' entity only. Just like searching on Google, you sometimes want to see a few pages of search results so that you can find the item that best meets your needs.  HMISLynk Search API provides up to 50 results for each searh. However, the search results can be limited by the client. Note: Current supporting URI  is /search/clients

                responses:
                  '200':
                    description: |
                      example: |
                        {
                        "searchResults": {
                          "pagination": {
                            "total":"2"
                            "from": "0",
                            "maximum": "50",
                            "returned":"2"
                          },
                          "items": [
                            {
                              "clientId": "65e3df62-dd22-4d07-83ef-6858a6322839",
                              "firstName": "Eric",
                              "middleName": "Eric",
                              "lastName": "Eric",
                              "nameSuffix": "NS ",
                              "nameDataQuality": "1",
                              "ssn": "ssn ",
                              "ssnDataQuality": "1",
                              "dob": "1459498034983",
                              "dobDataQuality": "1",
                              "race": "1",
                              "ethnicity": "1",
                              "gender": "1",
                              "otherGender": "Test",
                              "veteranStatus": "8",
                              "link":"/hmis-clientapi/rest/v2015/clients/65e3df62-dd22-4d07-83ef-6858a6322839"
                            },
                            {
                              "clientId": "cf98b9b2-9a77-4133-99a3-b60f05a12ad1",
                              "firstName": "Eric",
                              "middleName": "Eric",
                              "lastName": "Eric",
                              "nameSuffix": "NS ",
                              "nameDataQuality": "1",
                              "ssn": "ssn ",
                              "ssnDataQuality": "1",
                              "dob": "1459498034983",
                              "dobDataQuality": "1",
                              "race": "1",
                              "ethnicity": "1",
                              "gender": "1",
                              "otherGender": "Test",
                              "veteranStatus": "8",
                              "link":"/hmis-clientapi/rest/v2014/clients/cf98b9b2-9a77-4133-99a3-b60f05a12ad1"
                            }
                          ]
                        }
                        }

                queryParameters:
                  q:
                    description: |
                      The search keywords, as well as any qualifiers. Currently supported search fields are first name,middle name,last name,dob,source system id and ssn. For search on "date of birth" field the format MM-dd-YYYY should be used for the search keyword.
                  sort:
                    description: The sort field. Default- results are sorted by "created date".
                    example: created date
                    type: string
                  order:
                    description: The sort order if sort parameter is provided. One of asc or desc. Default- desc.
                    example: desc
                    default: desc
                    type: string
                  startIndex:
                    description: The start Index from where the search results should be returned. Default - 0
                    example: 0
                    default: 0
                    type: integer
                  maxItems:
                    description: the number or Items that should be included in the results . Default - 50
                    example: 50
                    default: 50
                    type: integer
                  exclude:
                    description: |
                      Excludes flieds from the search.Currently it suppoted value is "ssi" (to exclude         source system id) only.
              uriParameters:
                searchentity: {}
                /hmisTypes:
                  description: Get all available hmis types
                  get:
                    responses:
                      200:
                        body:
                          application/json:
                             example: !include examples/get_all_hmis_type_names.json
                             schema: !include schemas/get_all_hmis_type_names.json
                  /{name}/values:
                    description:  get all values of hmis type
                    get:
                      responses:
                        200:
                          body:
                            application/json:
                              example: !include examples/get_all_hmis_type_value_of_hmis_type.json
                              schema: !include types/get_all_hmis_type_value_of_hmis_type.json

                /questions:
                  get:
                    responses:
                      200:
                        body:
                          application/json:
                            example: !include examples/get_all_survey_questions.json
                            type: !include types/get_all_survey_questions.json
                /questions/{hudQuestionId}:
                  get:
                    responses:
                      200:
                        body:
                          application/json:
                            example: !include examples/get_survey_question_by_hudid.json
                            type: !include types/get_survey_question_by_hudid.json
